CREATE TABLE tbl_ideias (
IDEIA_CODIGO INT( 11 ) NOT NULL AUTO_INCREMENT,
IDEIA_ASSUNTO VARCHAR( 50 ) NOT NULL ,
IDEIA_CONTEUDO TEXT NOT NULL ,
IDEIA_NOME VARCHAR( 15 ) NOT NULL ,
IDEIA_DTCAD VARCHAR( 30 ) NOT NULL ,
IDEIA_DTALT VARCHAR( 30 ) NOT NULL ,
PRIMARY KEY ( IDEIA_CODIGO )
);

CREATE TABLE tbl_usuarios (
USUARIO_CODIGO INT( 11 ) NOT NULL AUTO_INCREMENT,
USUARIO_NOME VARCHAR( 50 ) NOT NULL ,
USUARIO_SNOME VARCHAR( 50 ) NOT NULL ,
USUARIO_EMAIL VARCHAR( 50 ) NOT NULL ,
USUARIO_PASS VARCHAR( 50 ) NOT NULL ,
USUARIO_NIVEL CHAR( 1 ) NOT NULL ,
USUARIO_CEL VARCHAR( 15 ) NOT NULL ,
USUARIO_DTCAD VARCHAR( 30 ) NOT NULL ,
USUARIO_DTALT VARCHAR( 30 ) DEFAULT NULL ,
PRIMARY KEY ( USUARIO_CODIGO )
);
